#!/usr/bin/env bash
#
# Runs GhostMap's EditMode test suites and prints a pass/fail summary per suite.
#
#   ./tools/run_unity_tests.sh                    # shared, viewer, scanner
#   ./tools/run_unity_tests.sh shared viewer      # a subset
#   ./tools/run_unity_tests.sh --rebuild-scenes   # regenerate Scanner.unity and Viewer.unity
#
# Environment:
#   UNITY_PATH            editor binary; overrides the search below
#   UNITY_VERSION         defaults to the pinned 6000.3.24f1
#   GHOSTMAP_TEST_OUTPUT  results directory, defaults to /tmp/ghostmap-tests
#   REBUILD_TIMEOUT       seconds before a scene rebuild is abandoned (420)
#
# Exit code is non-zero if any suite failed or did not run.
#
# All three suites run on macOS or Linux. ScannerIosPostBuild is guarded behind
# UNITY_IOS, so the scanner suite compiles without the iOS Build Support module;
# the iOS build itself still needs a Mac with Xcode. The viewer and scanner
# suites each re-run the whole shared suite through "testables".

set -uo pipefail

UNITY_VERSION="${UNITY_VERSION:-6000.3.24f1}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESULTS_DIR="${GHOSTMAP_TEST_OUTPUT:-/tmp/ghostmap-tests}"
REBUILD_TIMEOUT="${REBUILD_TIMEOUT:-420}"

find_unity() {
    if [[ -n "${UNITY_PATH:-}" ]]; then
        printf '%s' "$UNITY_PATH"
        return 0
    fi

    local candidate
    for candidate in \
        "/Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity" \
        "$HOME/Unity/Hub/Editor/$UNITY_VERSION/Editor/Unity" \
        "/opt/unity/editors/$UNITY_VERSION/Editor/Unity" \
        "/opt/Unity/Hub/Editor/$UNITY_VERSION/Editor/Unity"; do
        if [[ -x "$candidate" ]]; then
            printf '%s' "$candidate"
            return 0
        fi
    done

    return 1
}

project_for() {
    case "$1" in
        shared)  printf 'shared/TestProject' ;;
        viewer)  printf 'apps/viewer' ;;
        scanner) printf 'apps/scanner' ;;
        *)       return 1 ;;
    esac
}

# Totals come from the NUnit XML rather than the log, whose wording changes
# between Unity versions.
summarise() {
    local xml="$1"

    if [[ ! -f "$xml" ]]; then
        printf 'no results file'
        return 1
    fi

    python3 - "$xml" <<'PY'
import sys, xml.etree.ElementTree as ET

try:
    root = ET.parse(sys.argv[1]).getroot()
except ET.ParseError as exc:
    print(f"unreadable results XML ({exc})")
    sys.exit(1)

print(f"{root.get('total', '?')} tests, {root.get('passed', '?')} passed, "
      f"{root.get('failed', '?')} failed, {root.get('skipped', '0')} skipped")

failed = [c.get("fullname") or c.get("name")
          for c in root.iter("test-case")
          if c.get("result") not in (None, "Passed", "Skipped", "Inconclusive")]
for name in failed[:15]:
    print(f"    FAILED  {name}")
if len(failed) > 15:
    print(f"    ... and {len(failed) - 15} more")
PY
}

UNITY_BIN="$(find_unity)" || {
    cat >&2 <<EOF
Could not find Unity $UNITY_VERSION.

Set UNITY_PATH to the editor binary. The project pins $UNITY_VERSION; changing
it needs the dedicated dependency-change PR that AGENTS.md rule 10 requires.
EOF
    exit 1
}

mkdir -p "$RESULTS_DIR"
printf 'Unity:   %s\nResults: %s\n\n' "$UNITY_BIN" "$RESULTS_DIR"

# ---------------------------------------------------------------------------
# Scene regeneration. Both .unity files are generated by their scene builders.
# -executeMethod has been seen to hang in headless Unity at "Start Indexing";
# if that happens, use the GhostMap menu in the Editor instead.
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--rebuild-scenes" ]]; then
    status=0
    for suite in scanner viewer; do
        case "$suite" in
            scanner) method='GhostMap.Scanner.Editor.ScannerSceneBuilder.BuildScene'; menu='Build Scanner Scene' ;;
            viewer)  method='GhostMap.Viewer.Editor.ViewerSceneBuilder.BuildScene';   menu='Build Viewer Scene' ;;
        esac
        project="$(project_for "$suite")"
        log="$RESULTS_DIR/rebuild-$suite.log"
        printf '==> rebuilding %s scene\n' "$suite"

        # macOS has no `timeout` unless coreutils is installed.
        limiter=()
        if command -v timeout >/dev/null 2>&1; then
            limiter=(timeout "$REBUILD_TIMEOUT")
        elif command -v gtimeout >/dev/null 2>&1; then
            limiter=(gtimeout "$REBUILD_TIMEOUT")
        fi

        ${limiter[@]+"${limiter[@]}"} "$UNITY_BIN" -batchmode -nographics -quit \
            -projectPath "$REPO_ROOT/$project" -executeMethod "$method" \
            -logFile "$log" >/dev/null 2>&1
        rc=$?

        if [[ $rc -eq 0 ]]; then
            printf '    ok\n'
        elif [[ $rc -eq 124 ]]; then
            printf '    timed out after %ss; open %s and use GhostMap > %s\n' "$REBUILD_TIMEOUT" "$project" "$menu"
            status=1
        else
            printf '    exit %s, see %s\n' "$rc" "$log"
            status=1
        fi
    done
    [[ $status -eq 0 ]] && printf '\nScenes rebuilt. Commit the changed .unity files.\n'
    exit $status
fi

# ---------------------------------------------------------------------------
# Test suites.
# ---------------------------------------------------------------------------
if [[ $# -gt 0 ]]; then
    suites=("$@")
else
    suites=(shared viewer scanner)
fi

overall=0

for suite in "${suites[@]}"; do
    project="$(project_for "$suite")" || {
        printf 'Unknown suite "%s" (expected shared, viewer or scanner)\n' "$suite" >&2
        overall=1
        continue
    }

    xml="$RESULTS_DIR/$suite.xml"
    log="$RESULTS_DIR/$suite.log"
    rm -f "$xml"

    printf '==> %s (%s)\n' "$suite" "$project"

    "$UNITY_BIN" -batchmode -nographics \
        -projectPath "$REPO_ROOT/$project" \
        -runTests -testPlatform EditMode \
        -testResults "$xml" -logFile "$log" >/dev/null 2>&1
    rc=$?

    printf '    exit %s | %s\n' "$rc" "$(summarise "$xml")"

    if [[ $rc -ne 0 ]]; then
        overall=1
        if [[ ! -f "$xml" ]]; then
            printf '    no results written, most likely a compile error:\n'
            grep -E 'error CS[0-9]+|Compilation failed' "$log" 2>/dev/null | head -20 | sed 's/^/      /'
            printf '    full log: %s\n' "$log"
        fi
    fi
    printf '\n'
done

if [[ $overall -eq 0 ]]; then
    printf 'All requested suites passed.\n'
else
    printf 'At least one suite failed or did not run. Logs in %s\n' "$RESULTS_DIR"
fi

exit $overall
